agent_id = "2e85616c-c24f-4d91-b024-cba384ff3887"
name = "Mac.localdomain"
server_url = "http://localhost:8000"
api_key = ""
collection_interval = 30
heartbeat_interval = 60
tags = []

[p2p]
enabled = false
listen_port = 8443
peers = []
cert_path = "/etc/csf-agent/certs/agent.crt"
key_path = "/etc/csf-agent/certs/agent.key"
ca_cert_path = "/etc/csf-agent/certs/ca.crt"
auto_generate_certs = true
